import type { Edge } from "@xyflow/react";

import type { WorkflowEditorNode } from "@/types/node";
import type { Workflow, WorkflowRun } from "@/types/workflow";

const nodes: WorkflowEditorNode[] = [
  {
    id: "text-system",
    type: "workflowNode",
    position: { x: 80, y: 80 },
    data: {
      kind: "text",
      title: "Text Node",
      subtitle: "System prompt",
      accent: "#f5f5f5",
      icon: "align-left",
      status: "success",
      inputHandles: [],
      outputHandles: [{ id: "output", label: "Output", type: "text" }],
      text: "You are a professional marketing copywriter. Generate a compelling one-paragraph product description.",
      placeholder: "Enter text",
    },
  },
  {
    id: "text-details",
    type: "workflowNode",
    position: { x: 80, y: 300 },
    data: {
      kind: "text",
      title: "Text Node",
      subtitle: "Product details",
      accent: "#f5f5f5",
      icon: "align-left",
      status: "success",
      inputHandles: [],
      outputHandles: [{ id: "output", label: "Output", type: "text" }],
      text: "Product: Wireless Bluetooth Headphones. Features: Noise cancellation, 30-hour battery, foldable design.",
      placeholder: "Enter text",
    },
  },
  {
    id: "upload-image",
    type: "workflowNode",
    position: { x: 80, y: 560 },
    data: {
      kind: "upload-image",
      title: "Upload Image",
      subtitle: "Transloadit image input",
      accent: "#f97316",
      icon: "image",
      status: "success",
      inputHandles: [],
      outputHandles: [{ id: "output", label: "Image", type: "image" }],
      fileName: "headphones.webp",
      imageUrl:
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=960&q=80",
    },
  },
  {
    id: "crop-image",
    type: "workflowNode",
    position: { x: 420, y: 560 },
    data: {
      kind: "crop-image",
      title: "Crop Image",
      subtitle: "FFmpeg crop step",
      accent: "#ec4899",
      icon: "crop",
      status: "success",
      inputHandles: [
        { id: "image_url", label: "Image", type: "image", required: true },
        { id: "x_percent", label: "X", type: "number" },
        { id: "y_percent", label: "Y", type: "number" },
        { id: "width_percent", label: "Width", type: "number" },
        { id: "height_percent", label: "Height", type: "number" },
      ],
      outputHandles: [{ id: "output", label: "Output", type: "image" }],
      xPercent: "10",
      yPercent: "10",
      widthPercent: "80",
      heightPercent: "80",
    },
  },
  {
    id: "llm-copy",
    type: "workflowNode",
    position: { x: 820, y: 230 },
    data: {
      kind: "run-llm",
      title: "Run Any LLM",
      subtitle: "Gemini via Trigger.dev",
      accent: "#8b5cf6",
      icon: "sparkles",
      status: "running",
      inputHandles: [
        { id: "system_prompt", label: "System", type: "text" },
        { id: "user_message", label: "User", type: "text", required: true },
        { id: "images", label: "Images", type: "image", multiple: true },
      ],
      outputHandles: [{ id: "output", label: "Output", type: "text" }],
      model: "gemini-2.5-flash",
      systemPrompt: "",
      userMessage: "",
      result:
        "Introducing NextFlow-ready wireless headphones built for deep focus, travel, and everyday momentum.",
    },
  },
  {
    id: "upload-video",
    type: "workflowNode",
    position: { x: 80, y: 910 },
    data: {
      kind: "upload-video",
      title: "Upload Video",
      subtitle: "Transloadit video input",
      accent: "#38bdf8",
      icon: "film",
      status: "success",
      inputHandles: [],
      outputHandles: [{ id: "output", label: "Video", type: "video" }],
      fileName: "demo.mp4",
      videoUrl:
        "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    },
  },
  {
    id: "extract-frame",
    type: "workflowNode",
    position: { x: 430, y: 910 },
    data: {
      kind: "extract-frame",
      title: "Extract Frame",
      subtitle: "FFmpeg frame capture",
      accent: "#14b8a6",
      icon: "clapperboard",
      status: "success",
      inputHandles: [
        { id: "video_url", label: "Video", type: "video", required: true },
        { id: "timestamp", label: "Time", type: "text" },
      ],
      outputHandles: [{ id: "output", label: "Frame", type: "image" }],
      timestamp: "50%",
    },
  },
  {
    id: "text-social",
    type: "workflowNode",
    position: { x: 1120, y: 120 },
    data: {
      kind: "text",
      title: "Text Node",
      subtitle: "Social prompt",
      accent: "#f5f5f5",
      icon: "align-left",
      status: "success",
      inputHandles: [],
      outputHandles: [{ id: "output", label: "Output", type: "text" }],
      text: "You are a social media manager. Create a tweet-length marketing post based on the product image and video frame.",
      placeholder: "Enter text",
    },
  },
  {
    id: "llm-social",
    type: "workflowNode",
    position: { x: 1490, y: 420 },
    data: {
      kind: "run-llm",
      title: "Run Any LLM",
      subtitle: "Gemini via Trigger.dev",
      accent: "#8b5cf6",
      icon: "sparkles",
      status: "idle",
      inputHandles: [
        { id: "system_prompt", label: "System", type: "text" },
        { id: "user_message", label: "User", type: "text", required: true },
        { id: "images", label: "Images", type: "image", multiple: true },
      ],
      outputHandles: [{ id: "output", label: "Output", type: "text" }],
      model: "gemini-2.5-flash",
      systemPrompt: "",
      userMessage: "",
      result:
        "Meet the foldable noise-cancelling headphones that keep your soundtrack sharp from boarding gate to deep-work sprint.",
    },
  },
];

const edges: Edge[] = [
  {
    id: "text-system->llm-copy",
    source: "text-system",
    sourceHandle: "output",
    target: "llm-copy",
    targetHandle: "system_prompt",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
  {
    id: "text-details->llm-copy",
    source: "text-details",
    sourceHandle: "output",
    target: "llm-copy",
    targetHandle: "user_message",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
  {
    id: "upload-image->crop-image",
    source: "upload-image",
    sourceHandle: "output",
    target: "crop-image",
    targetHandle: "image_url",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
  {
    id: "crop-image->llm-copy",
    source: "crop-image",
    sourceHandle: "output",
    target: "llm-copy",
    targetHandle: "images",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
  {
    id: "upload-video->extract-frame",
    source: "upload-video",
    sourceHandle: "output",
    target: "extract-frame",
    targetHandle: "video_url",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
  {
    id: "text-social->llm-social",
    source: "text-social",
    sourceHandle: "output",
    target: "llm-social",
    targetHandle: "system_prompt",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
  {
    id: "llm-copy->llm-social",
    source: "llm-copy",
    sourceHandle: "output",
    target: "llm-social",
    targetHandle: "user_message",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
  {
    id: "crop-image->llm-social",
    source: "crop-image",
    sourceHandle: "output",
    target: "llm-social",
    targetHandle: "images",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
  {
    id: "extract-frame->llm-social",
    source: "extract-frame",
    sourceHandle: "output",
    target: "llm-social",
    targetHandle: "images",
    animated: true,
    className: "nextflow-edge",
    style: { stroke: "#7c3aed", strokeWidth: 2 },
  },
];

export const sampleWorkflow: Workflow = {
  id: "workflow-sample",
  userId: "demo-user",
  name: "Product Marketing Kit Generator",
  description:
    "Demonstrates all six node types, parallel branches, and a converging LLM summary.",
  nodes,
  edges,
  viewport: { x: 120, y: 200, zoom: 0.6 },
  createdAt: "2026-04-16T18:20:00.000Z",
  updatedAt: "2026-04-17T00:20:00.000Z",
};

export const sampleWorkflowRuns: WorkflowRun[] = [
  {
    id: "run-125",
    workflowId: sampleWorkflow.id,
    status: "running",
    target: "full",
    startedAt: "2026-04-17T00:19:00.000Z",
    finishedAt: null,
    durationMs: null,
    scopeNodeIds: sampleWorkflow.nodes.map((node) => node.id),
    nodeRuns: [
      {
        id: "node-run-1",
        nodeId: "crop-image",
        nodeKind: "crop-image",
        status: "success",
        durationMs: 1540,
        inputSummary: "headphones.webp",
        outputSummary: "Cropped product image uploaded to Transloadit",
        errorMessage: null,
        logs: ["Image cropped with FFmpeg inside Trigger.dev."],
      },
      {
        id: "node-run-2",
        nodeId: "llm-copy",
        nodeKind: "run-llm",
        status: "running",
        durationMs: null,
        inputSummary: "Marketing copy prompt + cropped image",
        outputSummary: "Awaiting Gemini response",
        errorMessage: null,
        logs: ["Queued in Trigger.dev.", "Waiting for Gemini response."],
      },
    ],
  },
  {
    id: "run-124",
    workflowId: sampleWorkflow.id,
    status: "partial",
    target: "selected",
    startedAt: "2026-04-16T22:12:00.000Z",
    finishedAt: "2026-04-16T22:12:06.000Z",
    durationMs: 6120,
    scopeNodeIds: ["crop-image", "llm-copy"],
    nodeRuns: [
      {
        id: "node-run-3",
        nodeId: "crop-image",
        nodeKind: "crop-image",
        status: "success",
        durationMs: 1500,
        inputSummary: "Product photo",
        outputSummary: "https://cdn.transloadit.com/cropped-image.webp",
        errorMessage: null,
        logs: ["Image cropped with FFmpeg inside Trigger.dev."],
      },
      {
        id: "node-run-4",
        nodeId: "llm-copy",
        nodeKind: "run-llm",
        status: "failed",
        durationMs: 3100,
        inputSummary: "Prompt + image",
        outputSummary: "No output",
        errorMessage: "Missing Gemini API key in environment.",
        logs: ["Gemini task started.", "Missing GOOGLE_GENERATIVE_AI_API_KEY."],
      },
    ],
  },
  {
    id: "run-123",
    workflowId: sampleWorkflow.id,
    status: "success",
    target: "single",
    startedAt: "2026-04-16T20:30:00.000Z",
    finishedAt: "2026-04-16T20:30:03.000Z",
    durationMs: 2800,
    scopeNodeIds: ["llm-social"],
    nodeRuns: [
      {
        id: "node-run-5",
        nodeId: "llm-social",
        nodeKind: "run-llm",
        status: "success",
        durationMs: 2800,
        inputSummary: "Social prompt + prior marketing copy + two images",
        outputSummary:
          "Meet the foldable noise-cancelling headphones that keep your soundtrack sharp from boarding gate to deep-work sprint.",
        errorMessage: null,
        logs: ["Gemini response generated via Trigger.dev."],
      },
    ],
  },
];
